# 异常

- 安全的语言 GC垃圾处理机制 ;
- 更加健壮；
- 程序不正常的事件：错误（Error） 和异常（Exception）
- 错误是代码解决不了；当错误出现之后 要么改动机器配置 要么改动源码

堆内存溢出

```java
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at com.qy50.edu.day230104.ErrorTest.main(ErrorTest.java:6)
```

栈内存溢出

```java
Exception in thread "main" java.lang.StackOverflowError
```

## 1.1.异常体系

-  Throwable是  Error 和 Exception 的父类型
- Error是所有错误的父类型
- Exception是所有异常的父类型
- Exception的后代类型主要划分为两大类 
  - 一类是运行时异常（只要是 RuntimeException的子类）
  -  一类是编译时异常（只要不是 RuntimeException的子类）

- 如果是 运行时异常  可以不处理编译也能通过，非受检异常
- 如果是 编译时异常  必须要处理编译才能通过，受检异常

## 1.2.异常的处理

### 1.2.1. try...catch..finally

1，try

- try{},try块是 有可能出现异常的代码
- 一旦出现异常 直接跳出try块 ；也就是说 下面的代码不再执行

2，catch

- catch(异常类型 异常名){ }
- 异常类型必须和抛出来的异常对象类型匹配（可以是后代类型的对象，向上转型） 才能抓到；
- 小类型在上面 大类型在下面

基本使用

```java
/**
     * 异常其实就是对象 是一个异常类型的对象
     *
     * @param op1
     * @param op2
     */
    public static void method3(int op1, int op2) {
        int num = 0;
        try {
            num = op1 / op2;
            //类型也可以写父类型 
        } catch (Exception e) {
            //向上转型
            // RuntimeException m = new ArithmeticException();
            System.out.println(e);
            // getMessage()获取异常对象的报错信息
            System.out.println(e.getMessage());
            //对异常进行处理
           /* op2 = 1;
            num = op1 / op2;
            System.out.println("catch num: " + num);*/
        }
        int sum = num + 10;
        System.out.println("+++++++++++++++");
    }
```

多重catch

```java
/**
     * 多重catch
     *
     * @param stringArr
     */
    public static void method4(String[] stringArr) {
        try {
            int i = Integer.parseInt(stringArr[0]);
        } catch (NullPointerException e) {
            System.out.println(e.getMessage());
        } catch (ArrayIndexOutOfBoundsException e) {
            //  System.out.println(e.getMessage());
            //打印堆栈的报错信息
            e.printStackTrace();
        } catch (NumberFormatException e) {
            System.out.println(e.getMessage());
            e.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        }
        System.out.println("++++++++++++++++++++++++");
    }

```

3，finally 

```java
public static void method6() {
        try {
            System.out.println(1 / 0);
        } finally {
            System.out.println();
        }
    }

    public static void method5() {
        try {
            System.out.println(1 / 2);
        } catch (NullPointerException e) {
            e.printStackTrace();
        } finally {
            //最终 一定会执行的代码 有关资源的释放的代码 必须要执行的 都会放到finally中
            System.out.println("一定会执行的代码");
        }
        System.out.println("++++++++++++");
    }
```

### 1.2.2. 抛异常

- throw出现在方法体中  throw 异常对象;
  - throw 和return一样 ；一旦执行 方法结束

- throws出现在方法声明处 表示此方法会抛出的异常类型（基本都是编译时异常类型，因为运行时异常类型不需要写）

1.运行时异常的抛出

```java
public class ExceptionExer2 {
    public static void main(String[] args) {
        method1();
        System.out.println("end");
    }

    public static void method1() {
        method2();
        System.out.println("method1执行到此");
    }

    /**
     * 异常对象只要在某个地方被抓住处理了 就不会再向上抛了
     */
    public static void method2() {
        try {
            method3();
        } catch (ArithmeticException e) {
            // e.printStackTrace();
        }
        System.out.println("method2执行到此");
    }

    /**
     * 运行时异常对象 可以被JVM自动创建 并且自动向上抛
     */
    public static void method3() {
        //JVM自动new了一个运行时 异常对象
        // ArithmeticException e = new ArithmeticException();
        //运行时异常对象 是自动被 抛出来的；throw一旦执行 效果等价于 return
        // throw e;
        int num = 1 / 0;
//        System.out.println(num);
    }
}
```

2，编译时异常的抛出

```java
public class ExceptionExer3 {
    public static void main(String[] args) {
        try {
            method1();
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }
    }

    public static void method1() throws FileNotFoundException {
        method2(null);
    }

    /**
     * throw出现在方法体中  throw 异常对象;
     * throws出现在方法声明处 表示此方法会抛出的异常类型（基本都是编译时异常类型，因为运行时异常类型不需要写）
     */
    // public static void method2(String str) throws FileNotFoundException, NullPointerException {
    public static void method2(String str) throws FileNotFoundException {
        if (str == null) {
            NullPointerException exception = new NullPointerException();
            //throw 和return一样 一旦执行 方法结束
            throw exception;
        }
        if (str.length() < 0) {
            FileNotFoundException exception2 = new FileNotFoundException();
            throw exception2;
        }
        boolean b = str.equals("y");
        if (b) {
        }
    }

    public static void method33() throws FileNotFoundException, PrinterException {
        method3("str");
    }

    public static void method3(String str) throws FileNotFoundException, PrinterException {
        if (str == null) {
            throw new FileNotFoundException();
        } else if (str.length() <= 0) {
            throw new PrinterException();
        }
    }
}
```

## 1.3.自定义异常

- 自定义一个类型 继承Exception体系中任何一个类都可以

```java
public class AgeInvalidException extends Exception {
    public AgeInvalidException() {
    }
    public AgeInvalidException(String message) {
        super(message);
    }
}
```

测试代码

```java
 private static void method2() {
        long num = 10L;
        try {
            method1(-1);
        } catch (AgeInvalidException e) {
            System.out.println(e.getMessage());
        }
    }

    public static void method1(int age) throws AgeInvalidException {
        if (age < 0 || age > 160) {
            throw new AgeInvalidException("年龄不合法");
        }
    }
```



## 1.4.编码要求

- **运行时异常** 一般不是通过 try。。catch进行处理，而是要进行参数的有效性校验

```java
 public static void maxArr(int[] arr) throws Exception {
        //参数的有效性校验
        if (arr == null) {
            System.out.println(" ");
            throw new NullPointerException("数组为null ");
        }

        if (arr.length <= 0) {
            throw new Exception("数组长度为0");
        }

        int max = arr[0];

        for (int i = 1; i < arr.length; i++) {
            max = max > arr[i] ? max : arr[i];
        }
        System.out.println("max: " + max);
    }

    public static void method4(int op1, int op2) {
        //参数的有效性校验
        if (op2 == 0) {
            op2 = 1;
        }

        int num = op1 / op2;

    }

    public static void method3(String str) {
        //对参数 做有效性校验
        if (str == null) {
            str = "java";
        }
        boolean b = str.startsWith("java");
        if (b) {

        } else {

        }
    }
```

